### ISSUE TITLE
Linux - Resolution menu doesent go away even after applying fixes

### ISSUE THREAD

**Issue by ldwlaldla** [Hypnootize/m0rehud#40] opened 2023-10-24 16:17 UTC
Hello, I installed m0rehud on arch linux as the only mod I have for tf2, however the resolution menu doesent go away even after pressing continue and adding the suggested lines into my autoexec from the troubleshooting section. I noticed that the m0re_resolution_scoreboard.txt file was empty even after selecting a resolution and closing tf2, and that the m0re_resolution_menu.txt looked fine with the contents of: ```X { HUD_Resolution_Menu { visible 0 } } ```
I dont know what the problem is or if the m0re_resolution_scoreboard.txt file being empty has anything to do with it, but it seemed strange.
Thanks in advance.

**Comment by Hypnootize** [comment] 2023-10-24 16:57
Hi, if you selected the `16:9` aspect ratio the `m0re_resolution_scoreboard.txt` will stay empty and that's just how it's supposed to work as the HUD is already setup for `16:9`.

You can hide the panel manually from `Resource/UI/Customizations/#Customization_Menu/HUD_Resolution_Menu.res` and in the file simply set the `"visible"` to `"0"` under `"HUD_Resolution_Menu"`, just so you can at least use the HUD.

Once you have that panel hidded could try activating some of the other customizations from the `HUD OPTIONS` menu and check if they work as intended?
I'll be honest, I don't have much experience with linux so I'm not sure if it could be a case where the system handles the config files in a different way than windows, or the game is not able to read the `.txt` files for some reason, it seems to be printing the code inside the `.txt` files just fine so the latter seems more likely to me.

**Comment by Hypnootize** [comment] 2023-10-25 19:49
After discussing it with some other developers seems like tweaking the #base lines to refere to the `tf/cfg` folder directly, as suggested [here](https://github.com/Hypnootize/m0rehud/pull/41), might be a possible solution.
I've created a new [branch](https://github.com/Hypnootize/m0rehud/tree/Linux) with a version featuring the mentioned tweaks so feel free to give it a shot and let me know if it works!

**Comment by narcissusTheFlower** [comment] 2023-11-05 19:27
Using files from https://github.com/Hypnootize/m0rehud/tree/Linux helped me as well. Thank you. I have it installed like this:
![2023-11-05_22-26](https://github.com/Hypnootize/m0rehud/assets/95850699/6fece88f-f327-4788-82ea-0dd21741aac1)

**Comment by Hypnootize** [comment] 2024-03-10 18:23
From the feedback I got seems like the newer version is working fairly well on Linux now, apart from certain fonts being oversized but that's a separate issue that I'll try to address soon. I'll close this for now and re-open if any problem related to the customization menu pops up!

**Closed by Hypnootize** 2024-03-10 18:23 UTC
